name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-Debug-Version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Apk Debug
        uses: actions/upload-artifact@v3
        with:
          name: debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  build-Release-Version:
    needs:
      - build-Debug-Version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Release Version
        run: ./gradlew assembleRelease

      - name: Upload Apk Release
        uses: actions/upload-artifact@v3
        with:
          name: release.apk
          path: app/build/outputs/apk/release/app-release.apk
  Alpha-PlayStore:
    needs:
      - build-Release-Version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Deploy Alpha PlayStore
        run: |
          ./gradlew assembleRelease
          ./gradlew promoteArtifact --promote-track alpha